### ISSUE TITLE
tests fail on python3.10

### ISSUE THREAD

**Issue by robbat2** [fknittel/python-fdsend#1]
I'm wondering what underlying thing changed in Python 3.10 that causes this test to fail. 

```
>>> Source compiled.
>>> Test phase: dev-python/fdsend-0.3.0
 * python3_8: running distutils-r1_run_phase python_test
python3.8 -m unittest_or_fail discover -v
test_negative_recv (fdsend.tests.TestFDSend)
fdsend.recvfds does not accept negative buffer lengths. ... ok
test_send_receive (fdsend.tests.TestFDSend)
Test sending and receiving of direct data and file descriptors. ... ok

----------------------------------------------------------------------
Ran 2 tests in 0.103s

OK
 * python3_9: running distutils-r1_run_phase python_test
python3.9 -m unittest_or_fail discover -v
test_negative_recv (fdsend.tests.TestFDSend)
fdsend.recvfds does not accept negative buffer lengths. ... ok
test_send_receive (fdsend.tests.TestFDSend)
Test sending and receiving of direct data and file descriptors. ... /var/tmp/portage-tmpfs/portage/dev-python/fdsend-0.3.0/work/python-fdsend-0.3.0/fdsend/tests.py:143: DeprecationWarning: PY_SSIZE_T_CLEAN will be required for '#' formats
  fdsend.sendfds(client_sock, self.DIRECT_DATA, fds=[tmp_fp])
ok

----------------------------------------------------------------------
Ran 2 tests in 0.103s

OK
 * python3_10: running distutils-r1_run_phase python_test
python3.10 -m unittest_or_fail discover -v
test_negative_recv (fdsend.tests.TestFDSend)
fdsend.recvfds does not accept negative buffer lengths. ... ok
test_send_receive (fdsend.tests.TestFDSend)
Test sending and receiving of direct data and file descriptors. ... FAIL

======================================================================
FAIL: test_send_receive (fdsend.tests.TestFDSend)
Test sending and receiving of direct data and file descriptors.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage-tmpfs/portage/dev-python/fdsend-0.3.0/work/python-fdsend-0.3.0/fdsend/tests.py", line 90, in test_send_receive
    self.receive_data()
  File "/var/tmp/portage-tmpfs/portage/dev-python/fdsend-0.3.0/work/python-fdsend-0.3.0/fdsend/tests.py", line 111, in receive_data
    self.assertEqual(len(fds), 1)
AssertionError: 0 != 1

----------------------------------------------------------------------
Ran 2 tests in 0.103s
```

**Comment by robbat2** [comment]
This looks like it should work
https://github.com/fknittel/python-fdsend/blob/master/fdsend/tests.py#L96-L127

**Comment by pkern** [comment]
It's actually failing to send, not failing to receive - a fact that is hidden by an `os.exit(1)` swallowing the exception:

```
======================================================================
ERROR: test_send_receive (fdsend.tests.TestFDSend)
Test sending and receiving of direct data and file descriptors.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pkern/src/python-fdsend/fdsend/tests.py", line 82, in test_send_receive
    self.send_data()
  File "/home/pkern/src/python-fdsend/fdsend/tests.py", line 146, in send_data
    fdsend.sendfds(client_sock, self.DIRECT_DATA, fds=[tmp_fp])
SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats
```

And that makes sense as this is a breaking change in Python 3.10.

**Comment by pkern** [comment]
PR #2 should fix this.
